#Exercise 63 - More for loops
#create a list that contains at least 20 different numbers unsorted
#write a loop that runs over all elements of the list and adds them all up
list_1 = [5,23,57,12,7,45,1,9,5,7,44,2,99,3,7,22,13,6,8,67,44]
sum_1 = 0

for i in list_1:
    sum_1 += i
print(f"The sum of your numbers is {sum_1}")
#Write a second loop that tells the user for each element
#whether it is bigger or lower than a number specified by him
#this number should be generated by using input before the start of the loop
no_1 = int(input("Give me a number\n"))
for i in list_1:
    if no_1 > i:
        print(f"Your number is bigger than {i}.")
    elif no_1 < i:
        print(f"Your number is smaller than {i}.")
    else:
        print("Your numbers are equal.")
